# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zhimeng-ZHu
email: 2895591970@qq.com
description: >- 
  Welcome to my official blog on computer vision, deep learning, and
  data science. Explore insights on AI research, image processing, and 
  embedded systems, alongside tutorials, project updates, and academic resources.

twitter_username: username
github_username: Zhimeng-ZHu
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 0 # amount of posts to show
# paginate_path: /page:num/
timezone: Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Zhimeng Zhu"
  avatar : "/assets/images/1.jpg"
  bio: "My awesome biography goes here. And you can visit my blog pages to learn more about me, please click the link: [**My Blogs**](https://happyrain.githubu.io)."
  location: "China, Hubei, Wuhan"
  employer: "Huazhong University of Science and Technology"
  email: "2895591970@qq.com" 
  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : #"https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory      : # URL
  orcid            : #"http://orcid.org/yourorcidurl"
  semantic         : # URL
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : #"academicpages"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  bluesky          : #"bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # URL

  links:
    
    - label: "Welcome to my Blogs"
      icon: "fas fa-fw fa-link"
      url: "https://happyrain0427.github.io"
      
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"
      
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Zhimeng-Zhu/"
      
  #  - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    url: "https://instagram.com/"
      
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/"

    - label: "QQ"
      icon: "fab fa-fw fa-qq"
      url: "/assets/images/qq.jpg"

    - label: "WeChat"
      icon: "fab fa-fw fa-weixin"
      url: "/assets/images/weixin.jpg"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
      
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Zhimeng-Zhu/"
      
   # - label: "Instagram"
   #   icon: "fab fa-fw fa-instagram"
   #   url: "https://instagram.com/"

   # - label: "YouTube"
   #   icon: "fab fa-fw fa-youtube"
   #   url: "https://www.youtube.com/"

    - label: "QQ"
      icon: "fab fa-fw fa-qq"
      url: "/assets/images/qq.jpg"

    - label: "WeChat"
      icon: "fab fa-fw fa-weixin"
      url: "/assets/images/weixin.jpg"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
